CREATE  TABLE IF NOT EXISTS `articles_new` (
  `id` INT(5) NOT NULL AUTO_INCREMENT ,
`URL` VARCHAR(200) NULL DEFAULT NULL ,
  `title` VARCHAR(200) NULL DEFAULT NULL ,
  `content` LONGTEXT NULL DEFAULT NULL ,
  `editor` TEXT NULL DEFAULT NULL ,
  `date_added` DATE NULL DEFAULT NULL ,
  `keywords` TEXT NULL DEFAULT NULL ,
  `description` TEXT NULL DEFAULT NULL ,
  `indexpage` TEXT NULL DEFAULT NULL ,
  `iconname` VARCHAR(100) NULL DEFAULT NULL ,
  `maxicons` INT(3) NOT NULL DEFAULT '25' ,
  `coltime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `ticker` INT(9) NOT NULL DEFAULT '100' ,
  PRIMARY KEY (`id`) );


CREATE  TABLE IF NOT EXISTS `articlelinks_new` (
  `id` INT(4) NOT NULL AUTO_INCREMENT ,
  `article_id` INT(5) NOT NULL ,
  `linktype` VARCHAR(1) NOT NULL DEFAULT 'X' ,
  `url` TEXT NULL DEFAULT NULL ,
  `image` VARCHAR(45) NULL DEFAULT NULL ,
  `title` VARCHAR(45) NULL DEFAULT NULL ,
  `writeup` TEXT NULL DEFAULT NULL ,
  `display` TINYINT(1) NOT NULL DEFAULT '1' ,
  `name` VARCHAR(200) NULL DEFAULT NULL ,
  `email` VARCHAR(200) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) );
